---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  namespace: argo
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-admin
type: kubernetes.io/service-account-token