apiVersion: batch/v1
kind: CronJob
metadata:
  name: herald
spec:
  timeZone: "America/Toronto"
  schedule: "0 13 * * *" # Runs daily at 1:00 PM EST
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: herald
            image: harbor.internal.coldbrewlabs.ca/library/herald:20251219
            imagePullPolicy: Always
            env:
            - name: CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: wtp-herald-secrets
                  key: CHANNEL_ID
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wtp-herald-secrets
                  key: SLACK_BOT_TOKEN
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wtp-herald-secrets
                  key: GOOGLE_API_KEY
            - name: WTP_API_BASE
              valueFrom:
                secretKeyRef:
                  name: wtp-herald-secrets
                  key: WTP_API_BASE
          restartPolicy: Never