---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-sa-role
  namespace: argo-events
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - list
  - update
  - get
  - create
  - delete