steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_NAME}/${_IMAGE_NAME}:${_VERSION}', '.']

  - name: 'docker:dind'
    script: |
      #!/bin/sh

      # Exit on error
      set -e

      apk add curl python3

      # Install RapidFort tooling
      if [ -z "$(command -v rflogin)" ] || [ "${RF_CLI_UPDATE}" == "yes" ]; then
        curl -ks "${RF_ROOT_URL}"/cli/ | sh
      fi

      # Stub the container image and upload metadata to console
      rfstub $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_NAME/$_IMAGE_NAME:$_VERSION -p $_RF_PROJECT_NUMBER

      # Rub the stubbed image
      docker run \
      --rm \
      -p 8000:8000 \
      --cap-add=SYS_PTRACE \
      --detach \
      --name $_IMAGE_NAME \
      $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_NAME/$_IMAGE_NAME:$_VERSION-rfstub

      # Create a Python virtual environment
      python3 -m venv cr-venv

      # Install required packages
      cr-venv/bin/pip install fastapi httpx pytest uvicorn

      # Run pytest to test application
      cr-venv/bin/pytest

      # Stop the running stubbed image
      docker stop $_IMAGE_NAME

      # Hardened the stubbed image
      rfharden $LOCATION-docker.pkg.dev/$PROJECT_ID/$_GAR_NAME/$_IMAGE_NAME:$_VERSION-rfstub
    env:
      - 'RF_ROOT_URL=https://us01.rapidfort.com'
      - 'RF_CLI_UPDATE=no'
    secretEnv: ['RF_ACCESS_ID', 'RF_SECRET_ACCESS_KEY']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_NAME}/${_IMAGE_NAME}:${_VERSION}-rfhardened']
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_NUMBER}/secrets/RF_ACCESS_ID/versions/latest
      env: 'RF_ACCESS_ID'
    - versionName: projects/${PROJECT_NUMBER}/secrets/RF_SECRET_ACCESS_KEY/versions/latest
      env: 'RF_SECRET_ACCESS_KEY'
options:
  automapSubstitutions: true # Required so we can use $PROJECT_ID, $_GAR_NAME, etc. in the script.
substitutions:
  _GAR_NAME: "rapidfort"
  _VERSION: "latest"
  _IMAGE_NAME: "rapidfort-demo"
  _RF_PROJECT_NUMBER: "8119"